version: '3'
services:
  postgres:
    image: postgres:alpine
    # container_name: postgres
    # restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  mysql:
    image: mysql:latest
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      # 如果sql文件没有指定数据库要这里指定
      MYSQL_DATABASE: dev
      TZ: Asia/Shanghai
    # volumes:
    #   - ./debug.sql:/docker-entrypoint-initdb.d/debug.sql
    ports:
      - '3306:3306'

  redis:
    image: redis:alpine
    # restart: always
    # environment:
    # 空密码
    # - ALLOW_EMPTY_PASSWORD=yes
    # command: ["--requirepass", "root"]
    command: 
      --requirepass 'root'
    ports:
      - '6379:6379'
        
  mongo:
    image: mongo:latest
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    command:
      --auth
    ports:
      - '27017:27017'